### ISSUE TITLE
Can't create new account

### ISSUE THREAD

**Issue by roninjedi78** [arshad-yaseen/markdx#14]
Whether I ask it to send me a magic link or attempt to register using my google account, it resets back to the login page and never lets me login.

**Comment by arshad-yaseen** [comment]
Hey @roninjedi78, thank you for your issue. We've temporarily paused new registrations because we are working on the new MarkDX, which will feature an even better UX/UI, enhanced AI support like inline code completions, and beautiful formatting, among other improvements. I hope you can wait patiently for it. ❤️

**Comment by roninjedi78** [comment]
Absolutely! Thank you for the update.
